### ISSUE TITLE
Trigger "in view" when page load and element is already in viewport (ie: no need for scrolling)

### ISSUE THREAD

**Issue by cyril88888** [jonataswalker/scroll-watcher#11]
Hi,

I'm using this script to automatically play videos when they fully come visible in viewport. However, there are few videos which area already fully visible when the page load => how to trigger the script for them ?

Thank you

**Comment by jonataswalker** [comment]
Hi @Cyriltra 

Try something like this:
```javascript
var watcher = new ScrollWatcher();
watcher.on('page:load', function (evt) {
  window.setTimeout(() => {
    if (watcher.windowAtBottom()) window.scrollBy(0, -1);
    else window.scrollBy(0, 1);
  }, 30);
});
```

**Comment by cyril88888** [comment]
Oh yes right, this is the part of the code that do the trick.
In my project, I use the ready event instead of the load event as the load event will take few secs more to be triggered as there are several videos to preload.
Thank you

Great script btw !
