### ISSUE TITLE
Onload event listener

### ISSUE THREAD

**Issue by v4n** [jonataswalker/scroll-watcher#3]
I use this package to play a video when the element is the viewport.

The only problem I have encountered is that when I reload the page and I have the video in my viewport it won't play until I trigger the scroll event.

It would be great having a `onload`/`onload:full` event listener that executes when an element has been added to the DOM, check if it's in the viewport and triggers the callback.

**Comment by jonataswalker** [comment]
Ahh yes @v4n this is a must. Are you able to come up with a PR?

**Comment by v4n** [comment]
@jonataswalker yes I can. A bit tight on work, so possibly later this week.

**Comment by jonataswalker** [comment]
@v4n 
Take a look at #5, to be used like:
```javascript
watcher.on('page:load', function (evt) {
  // trigger a scroll
  window.setTimeout(() => window.scrollBy(0, 1), 20);
});
```

**Comment by v4n** [comment]
@jonataswalker awesome!
